config/routes.rb
Rails.application.routes.draw do

  get 'page/home'

  get 'page/galeria'

  get 'page/audio'

  get 'guiriguirialaire' => 'page#guiriguiri'  , as:'guiri'

  get 'v/:slug' => 'page#video'
  get 'a/:slug' => 'page#audio'
  get 'g/:slug' => 'page#gale'

  get 'categoria/:tipo(/:category)' => 'page#section'   , as: 'seccion'

  

  get 'loadmore_categoria/:page/:tipo(/:category)' => 'page#load_section'   , as: 'loadmoresection'
  get 'loadmore/:lastid(/:tag)' => 'page#loadgrid' 

  get 'tag/:tag' => 'page#home' , as: 'tag'  , :defaults => { :tipo => 3 }
  
  get 'masvistos' => 'page#home' , as: 'masvistos'  , :defaults => { :tipo => 1 }
  get 'mascomentados' => 'page#home' , as: 'mascomentados'  , :defaults => { :tipo => 2 }

   root 'page#home'

end

app/models/archive.rb
class Archive < ActiveRecord::Base
	belongs_to :category
	belongs_to :channel
	has_many :media_files
	self.table_name =  "archive"

	def self.getType(slug , category = nil , nlimit = 100 , page = 0)

		page = page.to_i * nlimit

		case slug
		when 'Videos'
			tipo = 'V'
		when 'Galerias'
			tipo = 'G'
		when 'Audios'
			tipo = 'A'			
		end

		if !category.blank?
			if tipo == 'V'
					a = self.where("media_tag like ? " , "%"+category+"%")
				else
					category = Category.find_by tag: category
					a = self.where("category_id = ?" , category.id)
			end
			else
				a = self	
		end
		 a = a.where("media_type = ?" , tipo).order("date_publication DESC").limit(nlimit).offset(page)		
 		
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :archive

	def self.getType(slug)
		case slug
		when 'Videos'
			tipo = 'V'
		when 'Galerias'
			tipo = 'G'
		when 'Audios'
			tipo = 'A'			
		end

		self.where("seccion = ?" , tipo).order("name ASC")
 		
	end
end

app/models/channel.rb
class Channel < ActiveRecord::Base
end

app/models/media_file.rb
class MediaFile < ActiveRecord::Base
	belongs_to :archive
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def section

      @categories = Category.getType(params[:tipo])
      @tipo = params[:tipo]
      @category = params[:category]
      @archive = Archive.getType(params[:tipo] , params[:category] , 25)
      
  end

  

  def load_section

      
      @tipo = params[:tipo]
      @category = params[:category]

      @archive = Archive.getType(params[:tipo] , params[:category] , 25 , params[:page])
      render partial:"griditems" , locals: { archive: @archive} 

  end

  def home


    tipo = (params[:tipo].blank?)? 0 : params[:tipo]
    now = Date.today
    tree = (now - 3)
    case tipo
    when 0
      @archive = Archive.order("date_publication DESC").limit(25)
      @destacado = Archive.select("id").where("date_publication >= ? " , tree).order("num_views DESC").limit(10)  
    when 1

      @archive = Archive.where("date_publication >= ? " , tree).order("num_views DESC").limit(10)
      
    when 2
      @archive = Archive.where("date_publication >= ? and num_comment > 0 " , tree).order("num_comment DESC").limit(10)
    when 3
      @archive = Archive.where("media_tag like ? " , '%'+params[:tag]+'%').order("date_publication DESC").limit(25) 

    end
    
   # render text: tipo
  end


  def loadgrid

    page = params[:lastid].to_i * 25

    if !params[:tag].blank?
      @archive = Archive.where("media_tag like ? " , '%'+params[:tag]+'%').order("date_publication DESC").limit(25) 
    else
      @archive = Archive.order('date_publication DESC').limit(25).offset(page)
    end
    render partial:"griditems" , locals: { archive: @archive} 
  end



  def gale
     now = Date.today
    tree = (now - 3)
    @video = Archive.find_by slug_name:params[:slug]
    @related = Archive.where("media_tag like ? " , @video.media_tag).order("rand()").limit(7)
    @destacado = Archive.select("id").where("date_publication >= ? " , tree).order("num_views DESC").limit(10)
  end


  def audio
    now = Date.today
    tree = (now - 3)
    @video = Archive.find_by slug_name:params[:slug]
    @related = Archive.where("media_tag like ? " , @video.media_tag).order("rand()").limit(7)
    @destacado = Archive.select("id").where("date_publication >= ? " , tree).order("num_views DESC").limit(10)
  end

  def video

     now = Date.today
    tree = (now - 3)
    @video = Archive.find_by slug_name:params[:slug]
    @related = Archive.where("media_tag like ? " , @video.media_tag).order("rand()").limit(7)
     @destacado = Archive.select("id").where("date_publication >= ? " , tree).order("num_views DESC").limit(10)
  end

  def guiriguiri
    
    #@categories = Category.getType(params[:tipo])
    @archive = Archive.getType('Audios' , 'guiriguirialaire' , 10)
   
   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper

	def blank_image(item)
	  if item.image.blank?
	   image_path ("default-audio.jpg")
	  else
	    item.image
	  end
	end

	def type_archive(item)
		case item
		when 'A'
			"audio"
		when "V"
			"video"
		when "G"
			 "gale"
		end


	end


	def is_destacado(destacado , item)
		
			if !destacado.blank?
				result = destacado.find_all { |v| v.id == item }
				if !result.blank? 
				 	"<span>Destacado</span>"
				else
					""
				end 
			end
	end

	def get_tags(strtags)
		tags = strtags.split(/,/)
		str = ''
		tags.each do |p|
			 str += "<a href='/tag/#{p}'>#{p}</a> "
		end
		str
	end


	def getParentUrl(tipo)
				link_to "Todos los #{tipo}" , {controller: :page , action: :section  , tipo: tipo}
	end
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
  <title>Media Center</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "ur-aa503ebe-a77a-a418-4b2a-960c438084b6", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
<div class="wrap">
<div class="ad ad728">
	<%= image_tag "ad-top-banner.jpg" , width:"730" , height:"90" %>

<div class="extras">
<div class="radiobox"><a href="#">GD radio</a></div>
<div class="buscador">
<input type="text" class="form-control srch" placeholder="Buscar">
<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button></div>
</div></div>
<div id="topnav">
<div class="wrap">
     <nav>
				<ul>
                	<li><a href="#">HOME</a>
                    	<ul>
                            <li><a href="#">LINK 1</a></li>
                            <li><a href="#">LINK 2</a></li>
                            <li><a href="#">LINK 3</a></li>
                            <li><a href="#">LINK 4</a></li>
                            <li><a href="#">LINK 5</a></li>
                        </ul>
                    </li>
					<li><a href="#">Fútbol</a></li>
					<li><a href="#">Selecciones</a></li>
					<li><a href="#">Ligas</a></li>
                    <li><a href="#">+Deportes</a></li>
                    <li><a href="#">Media</a></li>
                    <li><a href="#">Estadísticas</a></li>
                    <li><a href="#">Opinión</a></li>
				</ul>
			</nav>
			<a href="#" id="navbtn">Menú</a>   </div></div>
</header>

 <!-- div content -->
<%= yield %>
 <!-- end -->
</div>



</body>



</html>

app/views/page/_disqus.html.erb
  <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'mceg'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/page/_griditems.html.erb
<% archive.each do |item| %>
		<div class="grid <%= type_archive(item.media_type) %>" data-no-turbolink>
		<%=raw is_destacado(@destacado , item.id) %>	
		<div class="imgholder" >
		<%= link_to image_tag(blank_image(item))  , {:controller=>'page' , :action=>type_archive(item.media_type) , :slug=>item.slug_name} %>
		</div>
		<%= link_to item.title , {:controller=>'page' , :action=>type_archive(item.media_type) , :slug=>item.slug_name}  , class:'link' %></a>
		<div class="meta"><%= item.date_publication.strftime("%a %d %m , %Y") %></div>
		</div>
	<% end %>

app/views/page/_header.html.erb
	<div class="wrap">
	<div class="logo"><%= image_tag "logo_elgraficocom.png" , width: 514 , height: 77 %></div>
	<div class="table">
	<div class="app-btns">
	<span>Descarga app</span>
	  <ul>
	    <li class="android-btn" target="_blank"><a href="http://www.elgrafico.com/apps/" target="_blank"></a></li>
	    <li class="apple-btn" target="_blank"><a href="http://www.elgrafico.com/apps/" target="_blank"></a></li>
	    <li class="window-btn" target="_blank"><a href="http://www.elgrafico.com/apps/" target="_blank"></a></li>
	  </ul>
	</div>

	<div class="portada-kiosko">
	<a href="http://kiosko.laprensagrafica.com/index.html?tpu=El%20Grafico" target="_blank"><img src="http://kiosko.laprensagrafica.com/xml_epaper/El%20Grafico/portadathmb.jpg" alt="" width="100"></a> 
	</div>
	</div>

	</div>
	<div class="clearfix"></div>

	<div class="wrap menumedia" data-no-turbolink>
	<ul>
	    <li><%= link_to "Portada" , root_url %></li>
	    <li><%= link_to "Videos" , seccion_path('Videos') %></li>
	    <li><%= link_to "Galerías" , seccion_path('Galerias') %></li>
	    <li><%= link_to "Audios" , seccion_path('Audios') %></li>
	    <li><%= link_to "+ Vistos" , masvistos_path() %></li>
	    <li><%= link_to "+ Comentados" , mascomentados_path() %></li>
	</ul>
	</div>

app/views/page/_playerbrightcove.html.erb
<!-- Start of Brightcove Player -->

<div style="display:none">

</div>

<!--
By use of this code snippet, I agree to the Brightcove Publisher T and C 
found at https://accounts.brightcove.com/en/terms-and-conditions/. 
-->

<script language="JavaScript" type="text/javascript" src="http://admin.brightcove.com/js/BrightcoveExperiences.js"></script>

<object id="myExperience3689897573001" class="BrightcoveExperience">
  <param name="bgcolor" value="#FFFFFF" />
  <param name="width" value="480" />
  <param name="height" value="270" />
  <param name="playerID" value="1253286408001" />
  <param name="playerKey" value="AQ~~,AAAAii5Rn2E~,7dLC61Bt4MPNfGIoPDB79hFp7u4_Qy5H" />
  <param name="isVid" value="true" />
  <param name="isUI" value="true" />
  <param name="dynamicStreaming" value="true" />
  
  <param name="@videoPlayer" value="<%= video_id %>" />
</object>

<!-- 
This script tag will cause the Brightcove Players defined above it to be created as soon
as the line is read by the browser. If you wish to have the player instantiated only after
the rest of the HTML is processed and the page load is complete, remove the line.
-->
<script type="text/javascript">brightcove.createExperiences();</script>

<!-- End of Brightcove Player -->

app/views/page/audio.html.erb
<div class="content">

    <%= render partial:"header"%>


<div class="wrap">

<div class="audios">
			<!--INICIA PLAYER DE AUDIO-->
		<%= image_tag @video.image %>
<div id="wrapper">
		  <audio preload="auto" controls>
				<source src="<%=  @video.media_files[0].url_file%>">
			
			</audio>
			
			

			
		</div></div>



<div class="info">
<h2><%= @video.title%></h2>
<p id="tags_p">
Tags: 
	<%=raw get_tags(@video.media_tag)%>
</p>
<span class='st_sharethis_hcount' displayText='ShareThis'></span>
<span class='st_facebook_hcount' displayText='Facebook'></span>
<span class='st_twitter_hcount' displayText='Tweet'></span>
<span class='st_linkedin_hcount' displayText='LinkedIn'></span>
<span class='st_pinterest_hcount' displayText='Pinterest'></span>
<span class='st_email_hcount' displayText='Email'></span>
</div>
<div class="clearfix"></div>
<div class="azul">
<div class="coments">
 <%= render partial: "disqus" %>
</div>
<div id="more">
<div id="container">

		<%= render partial: "griditems" , locals: { archive: @related}%>

</div>
</div>


</div>

</div>


</div>
<%= javascript_include_tag 'audioplayer', 'data-turbolinks-track' => false %>

<script>
	var audioplay;
	audioplay = function() {
		 $( 'audio' ).audioPlayer(); } ;

	$(window).load(audioplay);
	$(window).on('page:load', audioplay)

</script>
<!--SCRIPT AUDIO --> 

app/views/page/gale.html.erb
<div class="content">
	<%= render partial:"header"%>


<div class="wrap">
<div class="media">
<div class="galeria">
<div id="rg-gallery" class="rg-gallery">
<div class="rg-thumbs">
<!-- Elastislide Carousel Thumbnail Viewer -->
<div class="es-carousel-wrapper">
<div class="es-nav">
<span class="es-nav-prev">Previous</span>
<span class="es-nav-next">Next</span>
</div>
<div class="es-carousel">
<ul>
	<% @video.media_files.each do |p| %>
	<li><a href="#"><%= image_tag p.url_file  , "data-large"=>p.url_file ,"alt"=>"image03", "data-description"=>p.description %></a></li>
    
   <% end %>

</ul>
</div>
</div>
<!-- End Elastislide Carousel Thumbnail Viewer -->
</div><!-- rg-thumbs --></div>
</div>
<div class="info">
<h2><%= @video.title%></h2>
<p id="tags_p">
Tags: 
	<%=raw get_tags(@video.media_tag)%>
</p>
<span class='st_sharethis_hcount' displayText='ShareThis'></span>
<span class='st_facebook_hcount' displayText='Facebook'></span>
<span class='st_twitter_hcount' displayText='Tweet'></span>
<span class='st_linkedin_hcount' displayText='LinkedIn'></span>
<span class='st_pinterest_hcount' displayText='Pinterest'></span>
<span class='st_email_hcount' displayText='Email'></span>
</div></div>
<div class="clearfix"></div>
<div class="azul">
<div class="coments">
<%= render partial: "disqus" %>
</div>
<div id="more">
<div id="container">
	<%= render partial: "griditems" , locals: { archive: @related}%>
</div>
</div>


</div>

</div>


</div>

<script id="img-wrapper-tmpl" type="text/x-jquery-tmpl">	
			<div class="rg-image-wrapper">
				{{if itemsCount > 1}}
					<div class="rg-image-nav">
						<a href="#" class="rg-image-nav-prev">Previous Image</a>
						<a href="#" class="rg-image-nav-next">Next Image</a>
					</div>
				{{/if}}
				<div class="rg-image"></div>
				<div class="rg-loading"></div>
				<div class="rg-caption-wrapper">
					<div class="rg-caption" style="display:none;">
						<p></p>
					</div>
				</div>
			</div>
		</script>

<%= javascript_include_tag 'jquery.tmpl.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'jquery.easing.1.3', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'jquery.elastislide', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'gallery', 'data-turbolinks-track' => true %>

app/views/page/guiriguiri.html.erb
<div class="content">
	   <%= render partial:"header"%>


	<div class="wrap">
		<div class="audios">
			<%= image_tag 'guiri.jpg' %>
		<div id="wrapper">			
			<audio preload="auto" controls>
				<source src="<%=  @archive[0].media_files[0].url_file rescue nil %>">
			</audio>

		<ul id="playlist">
			<% @archive.each do |item| %>
		        <li class="active">
		            <a href="<%= item.media_files[0].url_file%>">
		                <%= item.title %>
		            </a>
		        </li>
	        <% end %>
    	</ul>
	
    	</div></div>


<div class="info">
<h2></h2>
	<p id="tags_p">
	 
	
	</p>
	<span class='st_sharethis_hcount' displayText='ShareThis'></span>
	<span class='st_facebook_hcount' displayText='Facebook'></span>
	<span class='st_twitter_hcount' displayText='Tweet'></span>
	<span class='st_linkedin_hcount' displayText='LinkedIn'></span>
	<span class='st_pinterest_hcount' displayText='Pinterest'></span>
	<span class='st_email_hcount' displayText='Email'></span>
</div>
<div class="clearfix"></div>

		<div class="azul">
	<div class="coments">
	 <%= render partial: "disqus" %>
	</div>
	<div id="more">
	<div id="container">

			

	</div>
	</div>


	</div>

</div>
<%= javascript_include_tag 'audioplayer', 'data-turbolinks-track' => false %>

<script>
	var audioplay;
	audioplay = function() {
		 $( 'audio' ).audioPlayer(); } ;

	$(window).load(audioplay);
	$(window).on('page:load', audioplay)

</script>
<script type='text/javascript'>//<![CDATA[ 
$(window).load(function(){
var audio;
var playlist;
var tracks;
var current;

init();
function init(){
    current = 0;
    audio = $('audio');
    playlist = $('#playlist');
    tracks = playlist.find('li a');
    len = tracks.length - 1;
    audio[0].volume = .70;
    playlist.find('a').click(function(e){
        e.preventDefault();
        link = $(this);
        current = link.parent().index();
        run(link, audio[0]);
    });
    audio[0].addEventListener('ended',function(e){
        current++;
        if(current == len){
            current = 0;
            link = playlist.find('a')[0];
        }else{
            link = playlist.find('a')[current];    
        }
        run($(link),audio[0]);
    });
}
function run(link, player){
        player.src = link.attr('href');
        par = link.parent();
        par.addClass('active').siblings().removeClass('active');
        audio[0].load();
        audio[0].play();
}
});//]]>  

</script>

app/views/page/home.html.erb
<div class="content">

	<%= render partial:"header"%>

	<section id="wrapper">
		<% if !params[:tag].blank?%>
		<p class="tag-busqueda">Tag: <strong><%= params[:tag] %></strong></p>
		<% end %>
	<div id="container" class="">


	<%= render partial: "griditems" , locals: { archive: @archive}%>
	

	</div>
	</section>
<div style="clear:both"></div>

</div>

<script type="text/javascript">
var count = 1;

$(window).scroll(function(event){
		event.preventDefault();
		if($(window).scrollTop() == $(document).height() - $(window).height()){
			console.log("Load more...");
				load_more();			
		}
	});
	
	function load_more(){

		var foo = 1;
		$.get("/loadmore/"+count,function(data){
			
			$("#container").append(data);

			do_on_load();
			setTimeout(repage , 500);
			//$("#paginaCanalCategoria").val(pagina+"/"+canal+"/"+categoria+"/"+tipo);
			count += 1;
		});
		//console.log(count);
	}
</script>

app/views/page/section.html.erb
<div class="content overflow">

    <%= render partial:"header"%>

<div class="wrap"> 
    <ul id="sidebar" class="sidebar">
        <h1 class="canal_titulo">Categorías</h1>

        <li class="first  current" style="margin-bottom:10px;">
            <%= getParentUrl(params[:tipo]) %>
        <ul class="sub_sidebar">
            <% @categories.each_with_index do |item, index| %>

            <li class=" <%= "first_channel" unless index == 0 %>" data-no-turbolink>
                 <% if item.tag == "guiriguirialaire" %>
                    <%= link_to item.name , guiri_path() %>
                    <% else %>
                    <%= link_to item.name , { controller: 'page' , action: :section , tipo: params[:tipo] , category: item.tag} %>
                  <% end %>  
            </li>
            <% end %>
       
        </ul>
        </li>
    </ul>

<section id="wrapper">
	
<div id="container" class="seccion">

    <%= render partial: "griditems" , locals: { archive: @archive}%>
</div>

</section>

</div>

</div>

<script type="text/javascript">
var count = 1;

$(window).scroll(function(event){
        event.preventDefault();
        if($(window).scrollTop() == $(document).height() - $(window).height()){
            console.log("Load more...");
                load_more();            
        }
    });
    
    function load_more(){

        var foo = 1;
        $.get("/loadmore_categoria/"+count+"/<%= @tipo%>/<%=@category %>",function(data){
            
            $("#container").append(data);

            do_on_load();
            setTimeout(repage , 300);
            //$("#paginaCanalCategoria").val(pagina+"/"+canal+"/"+categoria+"/"+tipo);
            count += 1;
        });
        //console.log(count);
    }
</script>

app/views/page/tag.html.erb
<div class="content">

	<%= render partial:"header"%>

	<section id="wrapper">
		
	<div id="container" class="">

	<%= render partial: "griditems" , locals: { archive: @archive}%>
	

	</div>
	</section>
<div style="clear:both"></div>

</div>

<script type="text/javascript">
var count = 1;

$(window).scroll(function(event){
		event.preventDefault();
		if($(window).scrollTop() == $(document).height() - $(window).height()){
			console.log("Load more...");
				load_more();			
		}
	});
	
	function load_more(){

		var foo = 1;
		$.get("/loadmore/"+count,function(data){
			
			$("#container").append(data);

			do_on_load();
			setTimeout(repage , 500);
			//$("#paginaCanalCategoria").val(pagina+"/"+canal+"/"+categoria+"/"+tipo);
			count += 1;
		});
		//console.log(count);
	}
</script>

app/views/page/video.html.erb
<div class="content">

    <%= render partial:"header"%>


<div class="wrap">
    <div class="videop">
        <!-- video bightcove -->
        <%= render partial: "playerbrightcove" , locals: { video_id: @video.media_files[0].url_file } %>
      
        <!-- end -->

    </div>

    <div class="info">
    <h2><%= @video.title%></h2>
    <p id="tags_p">
    Tags: 
        <%=raw get_tags(@video.media_tag)%>
    </p>
    <span class='st_sharethis_hcount' displayText='ShareThis'></span>
    <span class='st_facebook_hcount' displayText='Facebook'></span>
    <span class='st_twitter_hcount' displayText='Tweet'></span>
    <span class='st_linkedin_hcount' displayText='LinkedIn'></span>
    <span class='st_pinterest_hcount' displayText='Pinterest'></span>
    <span class='st_email_hcount' displayText='Email'></span>
    </div>
    <div class="clearfix"></div>
    <div class="azul">
    <div class="coments">
        <%= render partial: "disqus" %>
    </div>
    <div id="more">
    <div id="container">

            <%= render partial: "griditems" , locals: { archive: @related}%>
    </div>
    </div>


    </div>

</div>


</div>